### ISSUE TITLE
No on-response / last-response trigger

### ISSUE THREAD

**Issue by EvD92** [coderfin/byutv-jsonp#10]
Hey all,

not sure wether it should be posted here or not, but I'm not getting a response trigger from the byutv.
It does fetch the data correctly trough as seen trough google dev mode.

Any idea's ?
 

```
<link rel="import" href="../../bower_components/polymer/polymer.html">
<link rel="import" href="../polymer-app/shared-styles.html">

<dom-module id="contact-pagina">
 <template>
 <style include="shared-styles">
 :host {
 display: block;
 }
 </style>


  <byutv-jsonp
    auto
    id="ajax_members_get"
    method="GET"
    url="https://api.guildwars2.com/v2/guild/code/members"
    params='{"access_token":"code"}'
    handle-as="json"
    last-response="{{_c_studenten}}"
    on-response="members_get_response_handler">
  </byutv-jsonp>



 </template>
 <script>
 Polymer({
 is: 'contact-pagina',
 properties: {
   c_visible: {
     type: Boolean,                                      /* true when element is the active visible item */
     value: false,
     observer: '_initializing',
   },
 },
 _initializing : function() {
   if (this.c_visible) {
      console.log("about-pagina");
      this.members_get_request_handler();
   }
 },
 members_get_request_handler: function() {
   console.log("members_get_request_handler");
   this.$.ajax_members_get.contentType="application/json";
   this.$.ajax_members_get.body={
   };
   this.$.ajax_members_get.generateRequest();
 },

 members_get_response_handler: function(request) {
   console.log("members_get_response_handler aantal studenten="+request.detail.response.length);
   this._c_studenten = request.detail.response;
 },
 });
 </script>
</dom-module>

```

**Comment by coderfin** [comment]
You have an extra `</vaadin-grid-column>` before `</vaadin-grid>`.  Also, requests are not automatically performed.  If you want the request to fire automatically set the `auto` attribute.  There may be other issues but these are a few that I was.  Check out the docs here: http://coderfin.github.io/byutv-jsonp/components/byutv-jsonp/.  I would recommend isolating the `byutv-jsonp` portion to ensure that it works and then move on to the other stuff.

**Comment by EvD92** [comment]
I've moved the jsonp to a new page (and edited above), it does the request but the on-response method isn't fired.
In google developer I do get the right json file in "response" tab.

**Comment by coderfin** [comment]
I've looked into this some more.  It appears that JSONP is not supported by the API you are using.  See https://forum-en.guildwars2.com/forum/community/api/JSONP-callbacks and https://forum-en.guildwars2.com/forum/community/api/HTTP-access/.

A quick check confirms that this is the case.  Calling https://api.guildwars2.com/v2/colors?callback=byutv_jsonp_callback_53dc550fbdb94e37b128963115436e13&_=d2609539e5614bf0b2854755ffa84382 returns an array but the array is not properly wrapped in a `callback`.  **JSONP requires that the response be wrapped but the API you are using does not support this**.  The response is just `[
  1,
  2,
  3,
  4,
  5,
  6,
  7,
...
  1499,
  1537,
  1538,
  1539,
  1540,
  1541,
  1542
]`

byutv-jsonp will not help you with this problem.  You will need to look into `CORS`.

If you have any other questions feel free to ask.
