### ISSUE TITLE
Custom headers

### ISSUE THREAD

**Issue by sheldon-sminq** [coderfin/byutv-jsonp#2]
Ho do we send across custom headers like Authorization along with the request?

**Comment by coderfin** [comment]
My understanding is that this cannot be done with JSONP.  Have a look at the following Stackoverflow responses:
- http://stackoverflow.com/a/3350833
- http://stackoverflow.com/a/14174557
- http://stackoverflow.com/a/14154282
- http://stackoverflow.com/a/14174506
- http://stackoverflow.com/a/11725662

Also, you may want to take a look at [CORS](http://enable-cors.org/).
