### ISSUE TITLE
Handling html response

### ISSUE THREAD

**Issue by JesperKihlberg** [coderfin/byutv-jsonp#3]
Thank you for a great element! Is it possible to extend it to also be able to handle html/xml response data, e.g. using handle-as="xml"?

**Comment by coderfin** [comment]
Retrieving and parsing cross-domain XML or XML in general lies outside my intended use for this element and my use cases.  If you are interested in adding this functionality you could create a pull request.

**Comment by JesperKihlberg** [comment]
Thank you for your answer, I will look into how I can solve this.
