### ISSUE TITLE
Two way binding fails

### ISSUE THREAD

**Issue by jestrux** [coderfin/byutv-jsonp#4]
Hey there, I tried to use data binding in the params area but it completely failed. Any ideas?

**Comment by coderfin** [comment]
Have you looked at [Computed Properties](https://www.polymer-project.org/1.0/docs/devguide/observers#computed-properties)?
- http://stackoverflow.com/a/30322559/2344083

**Comment by coderfin** [comment]
If you continue to have problems feel free to re-open this issue.
