### ISSUE TITLE
byutv_jsonp_callback_2e4b1c14fc33498db037884b3aedd6eb is not defined

### ISSUE THREAD

**Issue by mitjarobic** [coderfin/byutv-jsonp#8]
Keep getting this. What am i missing?

**Comment by coderfin** [comment]
Do you have a code example of how you are using this element and any JavaScript you are writing that relates to the element?

**Comment by mitjarobic** [comment]
Figured it out. The url param was not set properly. 

Can i send only GET requests with jsonp?

**Comment by coderfin** [comment]
Yes, you can only send GET requests with JSONP.

http://stackoverflow.com/a/3860117/2344083
