### ISSUE TITLE
Basic Authentication using byutv-jsonp

### ISSUE THREAD

**Issue by itsDineth** [coderfin/byutv-jsonp#9]
I had been passing the credentials for Basic Authentication via the headers attribute of iron-ajax.

`'{"Authorization": "Basic ' + btoa("test" + ":" + "test") + '"}'`

However, this does not seem to work with the byutv-jsonp element. And neither passing the username and password via URL (i.e. test:test@api.com) works.

Is there another way to use Basic Auth with this element?

**Comment by coderfin** [comment]
JSONP does not work the same way as AJAX.  Sorry, there are no plans to support what you wan't even if it were possible.
